bebeauty/urls.py
from django.contrib import admin
from django.urls import path, include
from booking.views import Home, Gallery, Contact, ListBookings, AddBookingView
from booking.views import ViewBooking, EditBookingView, DeleteBookingView
from booking.views import CancelBookingView, AdminListView, AdminListTodayView
from booking.views import AdminListPastSevenDaysView, AdminListThisYearView
from booking.views import AdminListThisMonthView, AdminListNextSevenDaysView
from booking.views import AdminAddBookingView, AdminEditBookingView
from booking.views import AdminCancelBookingView, AdminDeleteBookingView
from treatment.views import TreatmentListView, ServicesListView


handler400 = 'booking.views.handler400'
handler403 = 'booking.views.handler403'
handler404 = 'booking.views.handler404'
handler500 = 'booking.views.handler500'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Home.as_view(), name='home'),
    path('gallery', Gallery.as_view(), name='gallery'),
    path('services', ServicesListView.as_view(), name='services'),
    path('contact', Contact.as_view(), name='contact'),
    path('price-list', TreatmentListView.as_view(), name='price-list'),
    path('bookings', ListBookings.as_view(), name='bookings'),
    path('booking', AddBookingView.as_view(), name='booking'),
    path('booking/<int:pk>',
         ViewBooking.as_view(),
         name='view-booking'),
    path('booking/<int:pk>/edit',
         EditBookingView.as_view(),
         name='edit-booking'),
    path('booking/<int:pk>/cancel',
         CancelBookingView.as_view(),
         name='cancel-booking'),
    path('booking/<int:pk>/delete',
         DeleteBookingView.as_view(),
         name='delete-booking'),
    path('accounts/', include('allauth.urls')),
    path('admin-bookings', AdminListView.as_view(), name='admin-bookings'),
    path('admin-bookings/today',
         AdminListTodayView.as_view(),
         name='admin-bookings-today'),
    path('admin-bookings/past_7_days',
         AdminListPastSevenDaysView.as_view(),
         name='admin-bookings-past-7'),
    path('admin-bookings/next_7_days',
         AdminListNextSevenDaysView.as_view(),
         name='admin-bookings-next-7'),
    path('admin-bookings/this-month',
         AdminListThisMonthView.as_view(),
         name='admin-bookings-this-month'),
    path('admin-bookings/this-year',
         AdminListThisYearView.as_view(),
         name='admin-bookings-this-year'),
    path('booking-admin',
         AdminAddBookingView.as_view(),
         name='admin-booking'),
    path('booking-admin/<int:pk>/edit',
         AdminEditBookingView.as_view(),
         name='admin-booking-edit'),
    path('booking-admin/<int:pk>/cancel',
         AdminCancelBookingView.as_view(),
         name='admin-booking-cancel'),
    path('booking-admin/<int:pk>/delete',
         AdminDeleteBookingView.as_view(),
         name='admin-booking-delete'),
]

booking/models.py
''' the model file for the Booking app '''
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from phonenumber_field.modelfields import PhoneNumberField
from treatment.models import Treatment

# Choices related to the booking form
TIMESLOTS = ((0, "9am-11am"), (1, "12pm-2pm"), (2, "3pm-5pm"), (3, "6pm-8pm"))
APPOINTMENT_STATUS = ((0, 'OK'), (1, 'CANCELLED'))


class Booking(models.Model):
    ''' The booking Model for clients '''
    booking_id = models.BigAutoField(primary_key=True, unique=True)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE,
        related_name="User")
    contact_no = PhoneNumberField(region="GB", null=False, blank=False)
    email = models.EmailField()
    treatment = models.ForeignKey(
        Treatment, on_delete=models.CASCADE,
        related_name="Treatment_Name"
        )
    booking_time = models.DateField(auto_now=True)
    appointment_date = models.DateField()
    appointment_slot = models.IntegerField(choices=TIMESLOTS)
    address_line_one = models.CharField(max_length=60)
    address_line_two = models.CharField(max_length=60, blank=True)
    address_line_three = models.CharField(max_length=60, blank=True)
    city = models.CharField(max_length=20)
    post_code = models.CharField(max_length=10)
    additional_info = models.TextField(max_length=300, blank=True)
    cancelled = models.IntegerField(choices=APPOINTMENT_STATUS, default=0)

    class Meta:
        ''' the meta data for the Booking model '''
        ordering = ['appointment_date', 'appointment_slot']
        constraints = [
            models.UniqueConstraint(
                fields=['appointment_date', 'appointment_slot'],
                name='unique_booking')
        ]

    def __str__(self):
        return f"Booking No. #{self.booking_id}"

    def __name__(self):
        return f"Booking No. {self.booking_id}"

    def get_absolute_url(self):
        ''' return back to the reverse url of the booking '''
        return reverse("view-booking", kwargs={'pk': self.pk})

treatment/models.py
'''The Treatment Model '''

from django.db import models
from django.urls import reverse

TREATMENTS = ((0, "Facial"), (1, "Make-Up"),
              (2, "Pedicure"), (3, "Manicure"), (4, "Hair Styling"))


class Treatment(models.Model):
    ''' The Treatment object model '''
    treatment_type = models.IntegerField(choices=TREATMENTS)
    treatment_name = models.CharField(max_length=60, unique=True)
    slug = models.SlugField(max_length=60, unique=True, primary_key=True)
    treatment_price = models.DecimalField(blank=False,
                                          max_digits=5, decimal_places=2)
    treatment_description = models.TextField()
    treatment_time = models.CharField(max_length=50)

    class _Meta:
        ''' meta data for the treatment model '''
        ordering = ['treatment_name']

    def __str__(self):
        return f"{self.treatment_name}"

    def __name__(self):
        return f" Treatment: {self.treatment_name}"

    def get_absolute_url(self):
        ''' a class function to return the absolute url of the model object '''
        return reverse("treatment-price/", kwargs={"slug": self.slug})

booking/views.py
''' the views to the booking app '''

import os

from datetime import date, timedelta
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView, DeleteView
from django.views.generic import UpdateView, DetailView, ListView, edit
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.core.mail import EmailMessage
from django.http import request
from .models import Booking
from .forms import BookingForm, CancelForm, AdminBookingForm
from .filters import AdminFilter

EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')


class Home(TemplateView):
    ''' The index home view '''
    template_name = 'index.html'


class Gallery(TemplateView):
    ''' the gallery view '''
    template_name = 'gallery.html'


class Contact(TemplateView):
    ''' the contact page view '''
    template_name = 'contact.html'


class ListBookings(ListView):
    ''' the users list of bookings view '''
    model = Booking
    queryset = Booking.objects.all().order_by('-booking_id')
    template_name = 'bookings.html'
    paginate_by = 6
    context_object_name = 'bookings'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user)


class ViewBooking(DetailView):
    ''' the detail view of a users booking '''
    template_name = 'booking_details.html'
    model = Booking
    template_name_suffix = '<int:pk>'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user)


class AddBookingView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    ''' The create booking view  '''
    context_object_name = 'bookings'
    template_name = 'booking_form.html'
    form_class = BookingForm
    success_message = 'Thank you for your booking.'

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.email = self.request.user.email
        name = form.instance.user
        tel = form.instance.contact_no.as_national
        treat = form.instance.treatment
        day = form.instance.appointment_date.strftime('%A')
        fdate = form.instance.appointment_date.strftime('%d/%m/%Y')
        slot = form.instance.get_appointment_slot_display()
        address = form.instance.address_line_one
        city = form.instance.city
        pcode = form.instance.post_code
        body = (
            f"Hello {name} ({tel}),\n\nYour '{treat}' "
            f"booking is on {day} - {fdate}, for {slot}. The address of the "
            f"booking will take place at is:\n{address},\n{city},\n{pcode}."
            "\n\nIf you have any questions regarding your booking, please"
            " do not hesitate to get into contact with us.\n\nBest Wishes"
            "\n\nThe BeBeauty Team\n\nTel: +44 7838 555 323\nEmail:"
            " info@BeBeauty.co.uk")
        form.save()
        email = EmailMessage(
            f"BeBeauty Booking Confirmation {form.instance.booking_id}",
            body,
            "info@BeBeauty.co.uk",
            [form.instance.email, EMAIL_HOST_USER],
        )
        email.send(fail_silently=False)
        return super().form_valid(form)


class EditBookingView(SuccessMessageMixin, UpdateView):
    ''' the edit booking view for a user '''
    template_name = 'booking_form.html'
    form_class = BookingForm
    model = Booking
    success_message = 'Your booking details has been updated.'

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.email = self.request.user.email
        name = form.instance.user
        tel = form.instance.contact_no.as_national
        treat = form.instance.treatment
        day = form.instance.appointment_date.strftime('%A')
        fdate = form.instance.appointment_date.strftime('%d/%m/%Y')
        slot = form.instance.get_appointment_slot_display()
        address = form.instance.address_line_one
        city = form.instance.city
        pcode = form.instance.post_code
        bookid = form.instance.booking_id
        body = (
            f"Hello {name} ({tel}),\n\nYour booking (ref: #{bookid})"
            f" has been updated. \n\n{treat},\n{day} - {fdate}, for "
            f"{slot}\n\nThe address of the booking will take place "
            f"at is:\n{address},\n{city},\n{pcode}.\n\nIf you have "
            f"any questions regarding your booking, please do not "
            f"hesitate to get into contact with us.\n\nBest Wishes"
            f"\n\nThe BeBeauty Team\n\nTel: +44 7838 555 323\n"
            f"Email: info@BeBeauty.co.uk")
        form.save()
        email = EmailMessage(
            f"BeBeauty Booking Confirmation {bookid}",
            body,
            "info@BeBeauty.co.uk",
            [form.instance.email, EMAIL_HOST_USER],
        )
        email.send(fail_silently=False)
        return super().form_valid(form)


class CancelBookingView(SuccessMessageMixin, UpdateView):
    ''' the user cancel booking view '''
    template_name = 'cancel_booking_form.html'
    form_class = CancelForm
    model = Booking
    success_message = 'Your booking has been cancelled'

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.email = self.request.user.email
        name = form.instance.user
        tel = form.instance.contact_no.as_national
        bookid = form.instance.booking_id
        body = (
            f"Hello {name} ({tel}),\n\nYour booking (ref: #{bookid})"
            f" has been cancelled.\n\n We are sorry you can't make the"
            f" appointment, We look forward to doing business with you "
            f"in the future.\n\nBest Wishes\n\nThe BeBeauty Team"
            f"\n\nTel: +44 7838 555 323\nEmail: info@BeBeauty.co.uk")
        form.save()
        email = EmailMessage(
            f"BeBeauty Booking Confirmation {form.instance.booking_id}",
            body,
            "info@BeBeauty.co.uk",
            [form.instance.email, EMAIL_HOST_USER],
        )
        email.send(fail_silently=False)
        return super().form_valid(form)

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user)


class DeleteBookingView(SuccessMessageMixin, DeleteView):
    ''' the user delete booking view '''
    template_name = 'delete_booking.html'
    model = Booking
    success_url = reverse_lazy('bookings')
    success_message = 'Your booking has been deleted.'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user)

    def delete(self, *args, **kwargs):
        messages.error(self.request, self.success_message)
        return super(DeleteBookingView, self).delete(request, *args, **kwargs)


class AdminListView(ListView):
    ''' the admins list of bookings view '''
    model = Booking
    template_name = 'admin-planner.html'
    queryset = Booking.objects.order_by('-appointment_date')
    paginate_by = 10
    context_object_name = 'bookings'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['today'] = date.today()
        context['filter'] = AdminFilter(self.request.GET, self.get_queryset(),)
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        return AdminFilter(self.request.GET, queryset=queryset).qs


class AdminListTodayView(ListView):
    ''' the admins list filtered today of bookings view '''
    model = Booking
    template_name = 'admin-planner.html'
    today = date.today()
    queryset = Booking.objects.filter(appointment_date=today)
    queryset.order_by('-appointment_date', 'appointment_slot')
    paginate_by = 10
    context_object_name = 'bookings'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['today'] = date.today()
        context['filter'] = AdminFilter(self.request.GET, self.get_queryset())
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        return AdminFilter(self.request.GET, queryset=queryset).qs


class AdminListPastSevenDaysView(ListView):
    ''' the amdins list filter past seven days of bookings views '''
    model = Booking
    template_name = 'admin-planner.html'
    sdate = date.today()
    edate = sdate - timedelta(days=7)
    queryset = Booking.objects.filter(appointment_date__range=[edate, sdate])
    queryset.order_by('appointment_date', 'appointment_slot')
    paginate_by = 10
    context_object_name = 'bookings'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['today'] = date.today()
        context['filter'] = AdminFilter(self.request.GET, self.get_queryset())
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        return AdminFilter(self.request.GET, queryset=queryset).qs


class AdminListNextSevenDaysView(ListView):
    ''' the admins list filter next seven days of bookings view '''
    model = Booking
    template_name = 'admin-planner.html'
    today = date.today()
    sdate = today + timedelta(days=1)
    edate = sdate + timedelta(days=7)
    queryset = Booking.objects.filter(appointment_date__range=[sdate, edate])
    queryset.order_by('-appointment_date', 'appointment_slot')
    paginate_by = 10
    context_object_name = 'bookings'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['today'] = date.today()
        context['filter'] = AdminFilter(self.request.GET, self.get_queryset())
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        return AdminFilter(self.request.GET, queryset=queryset).qs


class AdminListThisMonthView(ListView):

templates/admin-booking-modal.html
{% load static %}

<!-- Admin Booking Modal  HTML Template-->
<div class="modal fade" id="bookingModal{{booking.pk}}" tabindex="-1" aria-labelledby="bookingModal{{booking.pk}}Label" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title col-sm-5" id="bookingModal{{booking.pk}}" class="d-inline">Booking ref: <b>{{ booking.booking_id }}</b>
                </h3>
                <!-- Booking status-->
                {% if booking.cancelled == 1 %}
                <h3 class="col-sm-6" style="font-size:1.8em; color:crimson"><b> Cancelled</b></h3>
                {% endif %}
                <!--Close modal button-->
                <button type=" button" class="btn-close col-sm-1" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body admin-modal">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-1"></div>
                        <!--Booking details display-->
                        <div class="col-sm-5">
                            <h5>
                                <b>
                                    <u>Name</u>
                                </b>
                            </h5>
                            <p>{{ booking.user }}</p>
                            <h5>
                                <b>
                                    <u>Email</u>
                                </b>
                            </h5>
                            <p>{{ booking.email }}</p>
                            <h5>
                                <b>
                                    <u>Booking Date</u>
                                </b>
                            </h5>
                            <p>{{ booking.appointment_date }}</p>
                            <h5>
                                <b>
                                    <u>Booking Time</u>
                                </b>
                            </h5>
                            <p>{{ booking.get_appointment_slot_display }}</p>
                        </div>
                        <div class="col-sm-5">
                            <h5>
                                <b>
                                    <u>Tel No</u>
                                </b>
                            </h5>
                            <p>{{ booking.contact_no.as_national }}</p>
                            <h5>
                                <b>
                                    <u>Treatment</u>
                                </b>
                            </h5>
                            <p>{{ booking.treatment }}</p>
                            <h5>
                                <b>
                                    <u>Address</u>
                                </b>
                            </h5>
                            <p>{{ booking.address_line_one }}
                                {% if booking.adress_line_two == "" %}
                                <br>{{ booking.address_line_two }}
                                {% endif %}
                                {% if booking.adress_line_three == "" %}
                                <br>{{ booking.address_line_three }}
                                {% endif %}
                                <br>{{ booking.city }}
                                <br>{{ booking.post_code }}</p>
                        </div>
                        <div class="col-sm-1"></div>
                    </div>
                </div>
                <div class="container">
                    <div class="row">
                        <div class="col-sm-1"></div>
                        <div class="col-sm-10 modal-text">
                            <h5>
                                <b>
                                    <u>Client Notes & Requests</u>
                                </b>
                            </h5>
                            <p>{{ booking.additional_info }}</p>
                        </div>
                        <div class="col-sm-1"></div>
                    </div>
                    <div class="container">
                        <div class="text-center">
                            <br>
                            <br>
                            <!--Admin Buttons for Editing, Cancel and Delete-->
                            <a class="admin-btn custom-site-btn btn-remove-blue edit-but" href="{% url 'admin-booking-edit' booking.pk %}">Edit</a>
                            <a class="admin-btn custom-site-btn btn-remove-blue del-but" href="{% url 'admin-booking-cancel' booking.pk %}">Cancel</a>
                            <a class="admin-btn custom-site-btn btn-remove-blue nul-but" href="{% url 'admin-booking-delete' booking.pk %}">Delete</a>
                            <br>
                            <br>
                        </div>
                    </div>
                </div>
                <!--Close modal button-->
                <div class="modal-footer">
                    <button type="button" class="custom-site-btn btn-remove-blue edit-but hvr" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

templates/admin_booking_form.html
<!-- This is the admin booking form page HTML template -->

{% extends "base.html" %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}

<!--code to determine if viewer is staff to have accesss to this form and not just a normal user-->
{% if user.is_authenticated and user.is_staff %}

<!--Page Title-->
<br>
<div class="container">
    <div class="box-wrap">
        <h1 class="center-text title-font smaller-sub-title">Admin Booking</h1>
    </div>
</div>
<br>
<!--Booking Form Box-->
<div class="container booking-box">
    <br>
    <div class="container booking-form-font-size">
        <div class="row">
            <div class="col-sm-1 col-md-2"></div>
            <div class="col-lg-8">
                <!--Admin Booking Form-->
                <form method="POST">
                    {{ admin_booking_form | crispy }}
                    <div class="text-center">
                        <h2>Administrator Submit Booking:</h2>
                    </div>
                    <br>
                    {% csrf_token %}
                    {% crispy form %}

                </form>
            </div>
            <div class="col-sm-2"></div>
        </div>
        <br>
    </div>
    <div class="col-sm-2"></div>
</div>
<br>
<br>
<!--Return to Admin Planner Button-->
<div class="container g-0">
    <div class="text-center">
        <a class="custom-site-btn btn-remove-blue edit-but" href="{% url 'admin-bookings' %}">Return to Admin</a>
    </div>
</div>
<br>
<br>

{% endif %}

{% endblock %}

templates/cancel-booking.html
{% extends "base.html" %}

{% block content %}

{% if user.is_authenticated %}

<body>
    <div class="screen-container">
        <div class="container">
            <div class="box-wrap">
                <h3 class="center-text title-font sub-title">Cancel Booking</h3>
            </div>
        </div>
        <br>
        <div class="col-sm-3"></div>
        <div class="container col-sm-6 booking-box">
            <div class="row g-0">
                <div class="text-center">
                    <div class=" text-center delete-box-top-margin">
                        <h3>Cancel Booking</h3>
                    </div>
                    <hr>
                    <div class="row">
                        <p> Hi {{booking.user}} </p>
                        <br>
                        <br>
                        <p>Are you sure you wish to cancel this booking?</p>
                    </div>
                    <div class="container d-inline-flex justify-content-center delete-box-bottom-margin">
                        <a type="button" class="custom-site-btn line-height-setter btn-remove-blue nul-but nul-hvr" href="{% url 'view-booking' booking.pk %}">Return</a>
                        <form method="POST" action="{% url 'cancel-booking' booking.pk %}">
                            {% csrf_token %}
                            {{ booking.cancelled }}

                            {{ form | safe }}
                            <!-- 
                            { if form.cancelled == False %}
                            { form.cancelled.value = True }}
                            { endif %} -->

                            <input type="submit" name="Submit" value="Cancel Booking" class="custom-site-btn line-height-setter del-but" />
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-3"></div>
</body>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

{% endif %}

{% endblock %}

<!-- Inject this code below with update to cancel a booking -->
<!-- { if user.is_authenticated }
<form class="d-inline" action="{% url 'post_like' post.slug %}" method="POST">
    { csrf_token }
    { if liked  }

    <button type="submit" name="blogpost_id" value="{{post.slug}}" class="btn=like"><i
            class="fas fa-heart"></i></button> -->

templates/cancel_booking_form.html
<!-- This is the cancel booking page HTML template -->

{% extends "base.html" %}

{% load static %}

{% block content %}
<!--Authentication code check to see if user is authenticated to see this view-->
{% if user.is_authenticated or user.is_authenticated and user.is_staff %}

<body>
    <div class="screen-container">
        <div class="container">
            <div class="box-wrap">
                <!--Page Title depending on User-->
                {% if user.username and user.is_staff %}
                <h3 class="center-text title-font sub-title"> Admin Cancel Booking</h3>
                {% else %}
                <h3 class="center-text title-font sub-title">Cancel Booking</h3>
                {% endif %}
            </div>
        </div>
        <br>
        <!-- Cancel booking body -->
        <div class="col-sm-3"></div>
        <div class="container col-sm-6 booking-box">
            <div class="row g-0">
                <div class="text-center">
                    <div class=" text-center delete-box-top-margin">
                        <h3>Cancel Booking</h3>
                    </div>
                    <hr>
                    <div class="row">
                        <p> Hi {{ user.username }} </p>
                        <br>
                        <br>
                        <p>Are you sure you wish to cancel this booking?</p>
                    </div>
                    <div class="container d-inline-flex justify-content-center delete-box-bottom-margin">
                        {% if user.username and user.is_staff %}
                        <!--Buttons determined by user-->
                        <a class="custom-site-btn line-height-setter btn-remove-blue nul-but nul-hvr" href="{% url 'admin-bookings' %}">Return</a>
                        {% else %}
                        <a class="custom-site-btn line-height-setter btn-remove-blue nul-but nul-hvr" href="{% url 'view-booking' booking.pk %}">Return</a>
                        {% endif %}
                        <!-- Cancel booking forms determined by user -->
                        {% if user.username and user.is_staff %}
                        <form method="POST">
                            {% csrf_token %}
                            {{ form.cancelled.is_ | safe }}
                            {{form.cancelled}}
                            <input type="submit" name="Submit" value="Cancel Booking" class="custom-site-btn line-height-setter del-but" />
                        </form>
                        {% else %}
                        <form method="POST" action="{% url 'cancel-booking' booking.pk %}">
                            {% csrf_token %}
                            {{ form.cancelled.is_ | safe }}
                            {{form.cancelled}}
                            <input type="submit" name="Submit" value="Cancel Booking" class="custom-site-btn line-height-setter del-but" />
                        </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-3"></div>
</body>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

{% endif %}

{% endblock %}

templates/treatment-price.html
<!-- This is the Treatment Price Modal HTML template -->
{% load static %}

{% for treatment in treatments %}
<div class="modal fade" id="treatmentModal{{treatment.pk}}" tabindex="-1" aria-labelledby="treatmentModal{{treatment.pk}}Label" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="treatmentModal{{treatment.pk}}Label">{{ treatment.treatment_name }}</h3>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <!-- Treatment Body -->
            <div class="modal-body">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-1"></div>
                        <div class="col-sm-5">
                            <h5>
                                <b>
                                    <u>Treatment Type:</u>
                                </b>
                            </h5>
                            <p>{{ treatment.get_treatment_type_display }}</p>
                            <h5>
                                <b>
                                    <u>Price:</u>
                                </b>
                            </h5>
                            <p>£{{ treatment.treatment_price }}</p>
                        </div>
                        <div class="col-sm-5">
                            <h5>
                                <b>
                                    <u>Session Time:</u>
                                </b>
                            </h5>
                            <p>
                                Approx ~
                                {{ treatment.treatment_time }}</p>
                        </div>
                        <div class="col-sm-1"></div>
                    </div>
                </div>
                <div class="container">
                    <div class="row">
                        <div class="col-sm-1"></div>
                        <div class="col-sm-10 modal-text">
                            <h5>
                                <b>
                                    <u>Description</u>
                                </b>
                            </h5>
                            <p>{{ treatment.treatment_description }}</p>
                        </div>
                        <div class="col-sm-1"></div>
                    </div>

                </div>
                <div class="modal-footer">
                    {% if user.is_staff %}
                    <a class="no-text-dec pag-page-btn" href="{% url 'admin-booking' %}">Book Now</a>
                    {% else %}
                    <a class="no-text-dec pag-page-btn" href="{% url 'booking' %}">Book Now</a>
                    {% endif %}
                    <button type="button" class="custom-site-btn btn-remove-blue edit-but hvr" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>

{% endfor %}